# Generated by Django 2.1.12 on 2020-11-25 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geolocalizacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='destination',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='distance',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='location',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
