# Generated by Django 2.1.12 on 2020-11-23 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geolocalizacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='updated',
        ),
    ]
