# Generated by Django 2.1.12 on 2020-12-14 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geolocalizacion', '0005_auto_20201214_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='altura',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='calle',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
